import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12 text-text-700 space-y-6">
      <h1 className="text-2xl font-bold text-text-900">Terms of Service</h1>
      <p className="text-sm text-text-500">Last updated: March 2026</p>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-text-800">What this service does</h2>
        <p>
          greatneck.ai is an AI-powered assistant that helps you find
          information about Great Neck villages — codes, permits, events, and
          local info.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-text-800">Not legal or official advice</h2>
        <p>
          Answers are generated by AI and may contain errors. They are not a
          substitute for official village communications, legal advice, or
          professional guidance. Always verify important information with the
          relevant village office.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-text-800">Content sources</h2>
        <p>
          Information is sourced from publicly available village codes, community
          websites, and event listings. We do our best to keep it current but
          cannot guarantee accuracy or completeness.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-text-800">Use at your own risk</h2>
        <p>
          This service is provided &ldquo;as is&rdquo; without warranties of any kind. We
          are not liable for decisions made based on information provided by this
          service.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold text-text-800">Contact</h2>
        <p>
          Questions? Email us at{" "}
          <a href="mailto:contact@askmura.com" className="text-sage hover:underline">
            contact@askmura.com
          </a>.
        </p>
      </section>
    </div>
  );
}
